apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-emergency
  namespace: canary-demo
  labels:
    app: canary-app
    emergency: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-app
      emergency: "true"
  template:
    metadata:
      labels:
        app: canary-app
        emergency: "true"
    spec:
      containers:
      - name: canary-app
        image: canary-demo:latest
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: APP_VERSION
          value: "v2.0.0"
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: canary-app-config
              key: APP_NAME
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: canary-app-config
              key: LOG_LEVEL
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi 