apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-analysis
  namespace: canary-demo
  labels:
    app: canary-app
spec:
  args:
  - name: service-name
  - name: error-rate-threshold
  - name: interval
  - name: count
  metrics:
  - name: error-rate
    interval: "{{args.interval}}"
    count: "{{args.count}}"
    successCondition: result[0] <= {{args.error-rate-threshold}}
    provider:
      prometheus:
        address: http://prometheus-service.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_errors_total{service="{{args.service-name}}"}[5m])) / 
          sum(rate(http_requests_total{service="{{args.service-name}}"}[5m])) 